// <auto-generated />
using System;
using API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(SpaceContext))]
    [Migration("20231008164028_astronaut10")]
    partial class astronaut10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DATA_CLASSES.Agency", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("abbrev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("administrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("featured")
                        .HasColumnType("bit");

                    b.Property<string>("founding_year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("launchers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logo_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spacecraft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Agency");
                });

            modelBuilder.Entity("DATA_CLASSES.AstronautResponse", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int?>("age")
                        .HasColumnType("int");

                    b.Property<int?>("agencyid")
                        .HasColumnType("int");

                    b.Property<string>("bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date_of_birth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("date_of_death")
                        .HasColumnType("datetime2");

                    b.Property<string>("eva_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("first_flight")
                        .HasColumnType("datetime2");

                    b.Property<int?>("flights_count")
                        .HasColumnType("int");

                    b.Property<bool?>("in_space")
                        .HasColumnType("bit");

                    b.Property<string>("instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("landings_count")
                        .HasColumnType("int");

                    b.Property<DateTime?>("last_flight")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profile_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profile_image_thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("spacewalks_count")
                        .HasColumnType("int");

                    b.Property<string>("time_in_space")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wiki")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("agencyid");

                    b.ToTable("Astronauts");
                });

            modelBuilder.Entity("DATA_CLASSES.NasaDailyImageResponse", b =>
                {
                    b.Property<int>("DateId")
                        .HasColumnType("int");

                    b.Property<string>("Copyright")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HdUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DateId");

                    b.ToTable("NasaDailyImages");
                });

            modelBuilder.Entity("DATA_CLASSES.AstronautResponse", b =>
                {
                    b.HasOne("DATA_CLASSES.Agency", "agency")
                        .WithMany()
                        .HasForeignKey("agencyid");

                    b.OwnsOne("DATA_CLASSES.Status", "status", b1 =>
                        {
                            b1.Property<int>("AstronautResponseid")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("stausId")
                                .HasColumnType("int");

                            b1.HasKey("AstronautResponseid");

                            b1.ToTable("Astronauts");

                            b1.WithOwner()
                                .HasForeignKey("AstronautResponseid");
                        });

                    b.Navigation("agency");

                    b.Navigation("status");
                });
#pragma warning restore 612, 618
        }
    }
}
